[project]
name = "rl-experiments"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "gym>=0.26.2",
    "gymnasium>=1.1.1",
    "pygame>=2.6.1",
    "stable-baselines3>=2.6.0",
]
